### ISSUE TITLE
org.openrewrite.kubernetes.UpdateContainerImageName do not have option to update image digest

### ISSUE THREAD

**Issue by davidtam** [openrewrite/rewrite-kubernetes#45]
## What problem are you trying to solve?
When I use `org.openrewrite.kubernetes.UpdateContainerImageName`some of the image contains image digest.
I want to be able to update the tag and remove the digest (or perhaps have to option to specify a new digest)

## Describe the solution you'd like
add option `String` / `digestToUpdate` and some way to remove digest

## Have you considered any alternatives or workarounds?
Cannot think of one atm

## Are you interested in [contributing this feature to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#new-features)?

yes but I need to find out the situation in my company

**Comment by timtebeek** [comment]
Hi @davidtam ; thanks for the suggestion and offer to help! Indeed it doesn't make sense to retain an old digest when updating to a new container image name. Perhaps the best way to start is to add a new unit test to [UpdateContainerImageNameTest.java](https://github.com/openrewrite/rewrite-kubernetes/blob/main/src/test/java/org/openrewrite/kubernetes/UpdateContainerImageNameTest.java) to show exactly what you're looking to change in a draft PR? Then from there we can see what the required changes would be to the recipe. Initially I'd start with removing any digest, as I think it's most common for folks to want to update to a new tag.

**Comment by DavidTamLloyds** [comment]
@timtebeek thank you - I have an approval to contribute now and I will start from what you have said

**Comment by timtebeek** [comment]
Fixed in
- https://github.com/openrewrite/rewrite-kubernetes/pull/46

Thanks again!
